export const JOB_USERS_REQUEST = 'JOB_USERS_REQUEST'
export const JOB_USERS_SUCCESS = 'JOB_USERS_SUCCESS'
export const JOB_USERS_FAIL = 'JOB_USERS_FAIL'

export const JOB_CREATE_REQUEST = 'JOB_CREATE_REQUEST'
export const JOB_CREATE_SUCCESS = 'JOB_CREATE_SUCCESS'
export const JOB_CREATE_FAIL = 'JOB_CREATE_FAIL'